name: CI build

on:
  # Trigger the workflow on pushes to only the 'main' branch (this avoids duplicate checks being run e.g. for dependabot pull requests)
  push:
    branches: [main, dev]
  # Trigger the workflow on any pull request
  pull_request:
  workflow_dispatch:

jobs:
  dist:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            code-target: win32-x64
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            code-target: win32-arm64
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            code-target: linux-x64
          - os: ubuntu-20.04
            target: aarch64-unknown-linux-gnu
            code-target: linux-arm64
          # - os: ubuntu-20.04
          #   target: armv7-unknown-linux-gnueabihf
          #   code-target: linux-armhf
          - os: macos-12
            target: x86_64-apple-darwin
            code-target: darwin-x64
          - os: macos-12
            target: aarch64-apple-darwin
            code-target: darwin-arm64

    env:
      LLM_LS_TARGET: ${{ matrix.target }}

    name: dist (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}
          
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          repo: smallcloudai/refact-lsp
          branch: main 
          path: ./assets
          name: dist-${{ matrix.target }}

      - name: Install VSCE
        run: |
          npm install
          npm install -g @vscode/vsce

      - name: Pakckage VSCE extension
        run: |
          chmod +x ./assets/refact-lsp*
          vsce package --target ${{ matrix.code-target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vscode-plugin-${{ matrix.target }}
          path: ./*.vsix
